version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 14
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    cooldown:
      default-days: 14
    directories:
      - docker/**/*
    schedule:
      interval: weekly

  - package-ecosystem: helm
    cooldown:
      default-days: 14
    directories:
      - charts/**/*
    exclude-paths:
      - charts/ai-service/** # deprecated chart
    schedule:
      interval: weekly
