version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 14
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    cooldown:
      default-days: 14
    directories:
      - docker/**/*
    schedule:
      interval: daily

  - package-ecosystem: helm
    cooldown:
      default-days: 14
    directories:
      - charts/**/*
    schedule:
      interval: weekly
