# SPDX-SnippetBegin
# SPDX-License-Identifier: Apache License 2.0
# SPDX-SnippetCopyrightText: 2024 © Argo Project, argoproj/argo-helm
# SPDX-SnippetCopyrightText: 2024 © Unique AG
# SPDX-SnippetEnd
## Reference: https://github.com/helm/chart-releaser
# index-path: "./index.yaml"

# PGP signing
# todo: not yet signing, to be added asap
# --> sign: true
# --> key: XXXXXX
# keyring:          # Set via env variable CR_KEYRING
# passphrase-file:  # Set via env variable CR_PASSPHRASE_FILE

# Enable automatic generation of release notes using GitHubs release notes generator.
# see: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
generate-release-notes: true
