apiVersion: v2
type: application
icon: https://www.unique.ch/hubfs/unique_assets/favicon/glyph_caumasee.svg
maintainers:
  - name: unique-ag
    url: https://unique.ch/
name: kong-plugins
version: 1.0.1
description: |
  The 'kong-plugins' chart provides a streamlined solution for deploying Kong plugins via ConfigMaps to be used with the Unique Software.

  Refer to each plugins readme section to learn more about them.

  Please report any security concerns with the plugins via the [Security Policy](https://github.com/Unique-AG/helm-charts/tree/main?tab=security-ov-file).
annotations:
  artifacthub.io/changes: |
    - Fixes breaking line breaks in the lua scripts