#
# EXAMPLE VALUES FOR EXTRA CRONJOBS
# Uses cronJob and extraCronJobs to define a CronJob and an extra CronJob
# 
env:
  FOO: quux
extraCronJobs:
  foo:
    concurrencyPolicy: Forbid
    env:
      FOO: BAR
    envVars:
      - name: BAZ
        value: qux
    failedJobsHistoryLimit: 3
    name: foo
    restartPolicy: Never
    schedule: 0 0 1 1 *
    startingDeadlineSeconds: 600
    successfulJobsHistoryLimit: 3
    suspend: false
    timeZone: Europe/Zurich
image:
  repository: uniquecr.azurecr.io/backend-service-ecj
  tag: '2024.40'
podSecurityContext: {}
secretProvider:
  tenantId: 16f4983c-5f9c-4004-a229-175cc3xampl4
  useVMManagedIdentity: 'true'
  userAssignedIdentityID: 16f4983c-5f9c-4004-a229-175cc3xampl4
  vaults:
    ut-ecj-service:
      DATABASE_URL: DATABASE-URL
      ZITADEL_PAT: ZITADEL-PAT
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault