{{- if .Values.hooks }}
  {{- $hasEnabledHook := false }}
  {{- range $hookName, $hookConfig := .Values.hooks }}
    {{- if and $hookConfig $hookConfig.enabled }}
      {{- $hasEnabledHook = true }}
    {{- end }}
  {{- end }}
  {{- if $hasEnabledHook -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backendService.fullname" . }}-hooks-env
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "4"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  {{- range $key, $value := .Values.inlineEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{/* Static values are added last so that they override the dynamic values (avoids regression and breaking changes) */}}
  VERSION: "{{ include "backendService.imageTag" . }}"
  {{- end }}
{{- end }}
