{{- if and .Values.secretProvider .Values.hooks }}
  {{- $hasEnabledHook := false }}
  {{- range $hookName, $hookConfig := .Values.hooks }}
    {{- if and $hookConfig $hookConfig.enabled }}
      {{- $hasEnabledHook = true }}
    {{- end }}
  {{- end }}
  {{- if $hasEnabledHook -}}
{{- $tenantId := .Values.secretProvider.tenantId | required ".Values.secretProvider.tenantId is required." -}}
{{- $userAssignedIdentityID := .Values.secretProvider.userAssignedIdentityID | required ".Values.secretProvider.userAssignedIdentityID is required." -}}
{{- $fullName := include "backendService.fullname" . -}}
{{- $labels := include "backendService.mutableLabels" . -}}
{{- range $k, $v := .Values.secretProvider.vaults }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $fullName }}-{{ $k }}-hooks
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  provider: azure
  secretObjects:
    - secretName: {{ $fullName }}-{{ $k }}-hooks
      labels:
        {{- $labels | nindent 8 }}
      data:
        {{- range $value := $v }}
        - key: {{ $value }}
          objectName: {{ $value }}
        {{- end }}
      type: Opaque
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $userAssignedIdentityID }}
    keyvaultName: {{ $k }}
    objects: |
      array:
        {{- range $value := $v }}
        - |
          objectName: {{ $value }}
          objectType: secret
        {{- end }}
    tenantId: {{ $tenantId }}
{{- end }}
{{- end }}
{{- end }}
