apiVersion: v2
type: application
icon: https://www.unique.ch/hubfs/unique_assets/favicon/glyph_caumasee.svg
maintainers:
  - name: unique-ag
    url: https://unique.ch/
name: web-app
version: 4.4.0
# change on next major: enable netpol by default
description: |
  The 'web-app' chart is a "convenience" chart from Unique AG that can generically be used to deploy web-content serving workloads to Kubernetes.

  Note that this chart assumes that you have a valid contract with Unique AG and thus access to the required Docker images.
sources:
  - https://github.com/Unique-AG/helm-charts/tree/main/charts/web-app
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Possibility to define volumes and volumeMounts"
