deprecated: true
apiVersion: v2
type: application
icon: https://www.unique.ch/hubfs/unique_assets/favicon/glyph_caumasee.svg
maintainers:
  - name: unique-ag
    url: https://unique.ch/
name: ai-service
sources:
  - https://github.com/Unique-AG/helm-charts/tree/main/charts/ai-service
version: 3.0.0
description: |
  Version 3.0.0 is the last supported iteration of this chart. Subsequent changes will only be supplied to https://artifacthub.io/packages/helm/unique/backend-service. Refer to End of Life Notice in README.md.
annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: "BREAKING: Pod identity support. The aadPodIdBinding annotation and usePodIdentity parameter have been removed."
